version: "3"
services:
  vpn-proxy:
    hostname: "vpn-proxy"
    container_name: "vpn-proxy"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DATABASE_URL=sqlite:///./data/vpnproxy.db"
      - "GLUETUN_IMAGE=qmcgaw/gluetun:latest"
    image: "ghcr.io/cyb3rgh05t/vpn-proxy:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    ports:
      - "5000:5000"
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/vpn-proxy/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
