"""Default templates seeded on first startup if app_templates table is empty."""

DEFAULT_APP_TEMPLATES = [
    {
        "id": "qbittorrent",
        "title": "qBittorrent",
        "subtitle": "Torrent client behind VPN",
        "image": "linuxserver/qbittorrent:latest",
        "suggested_name": "app-qbittorrent",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
            {"key": "WEBUI_PORT", "value": "8080"},
        ],
        "ports": [{"host": "8080", "container": "8080", "protocol": "tcp"}],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/downloads", "mode": "rw"},
        ],
        "devices": [],
        "labels": [],
    },
    {
        "id": "prowlarr",
        "title": "Prowlarr",
        "subtitle": "Indexer manager",
        "image": "linuxserver/prowlarr:latest",
        "suggested_name": "app-prowlarr",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
        ],
        "ports": [{"host": "9696", "container": "9696", "protocol": "tcp"}],
        "volumes": [{"source": "", "target": "/config", "mode": "rw"}],
        "devices": [],
        "labels": [],
    },
    {
        "id": "sonarr",
        "title": "Sonarr",
        "subtitle": "TV library manager",
        "image": "linuxserver/sonarr:latest",
        "suggested_name": "app-sonarr",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
        ],
        "ports": [{"host": "8989", "container": "8989", "protocol": "tcp"}],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/tv", "mode": "rw"},
            {"source": "", "target": "/downloads", "mode": "rw"},
        ],
        "devices": [],
        "labels": [],
    },
    {
        "id": "radarr",
        "title": "Radarr",
        "subtitle": "Movie library manager",
        "image": "linuxserver/radarr:latest",
        "suggested_name": "app-radarr",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
        ],
        "ports": [{"host": "7878", "container": "7878", "protocol": "tcp"}],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/movies", "mode": "rw"},
            {"source": "", "target": "/downloads", "mode": "rw"},
        ],
        "devices": [],
        "labels": [],
    },
    {
        "id": "jellyfin",
        "title": "Jellyfin",
        "subtitle": "Media server",
        "image": "linuxserver/jellyfin:latest",
        "suggested_name": "app-jellyfin",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
        ],
        "ports": [
            {"host": "8096", "container": "8096", "protocol": "tcp"},
            {"host": "8920", "container": "8920", "protocol": "tcp"},
        ],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/data/media", "mode": "rw"},
        ],
        "devices": [],
        "labels": [],
    },
    {
        "id": "plex",
        "title": "Plex Media Server",
        "subtitle": "Stream your media library behind VPN (blocks analytics)",
        "image": "linuxserver/plex:latest",
        "suggested_name": "app-plex",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "PUID", "value": "1000"},
            {"key": "PGID", "value": "1000"},
            {"key": "TZ", "value": "Europe/Berlin"},
            {"key": "VERSION", "value": "docker"},
        ],
        "ports": [{"host": "32400", "container": "32400", "protocol": "tcp"}],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/tv", "mode": "ro"},
            {"source": "", "target": "/movies", "mode": "ro"},
        ],
        "devices": ["/dev/dri:/dev/dri"],
        "labels": [],
    },
    {
        "id": "o11-panel",
        "title": "O11 Panel",
        "subtitle": "Generic O11 / OTT panel template",
        "image": "o11/panel:latest",
        "suggested_name": "o11-panel",
        "restart_policy": "unless-stopped",
        "env_vars": [
            {"key": "TZ", "value": "Europe/Berlin"},
            {"key": "ADMIN_USERNAME", "value": "admin"},
            {"key": "ADMIN_PASSWORD", "value": "changeme"},
        ],
        "ports": [
            {"host": "8080", "container": "8080", "protocol": "tcp"},
            {"host": "8443", "container": "8443", "protocol": "tcp"},
        ],
        "volumes": [
            {"source": "", "target": "/config", "mode": "rw"},
            {"source": "", "target": "/var/lib/mysql", "mode": "rw"},
        ],
        "devices": [],
        "labels": [],
    },
]
